### ISSUE TITLE
Would it be possible to configure jest/jest-watch-typeahead to start without running tests?

### ISSUE THREAD

**Issue by alexbjorlig** [jest-community/jest-watch-typeahead#116]
We are using jest and jest-watch-typeahead for some integration tests.

Sometimes the tests take a while to "exit", and it made us wonder if it would be possible to start on this screen as default?

![Screen Shot 2022-01-05 at 20 58 00](https://user-images.githubusercontent.com/9967422/148280982-d3c205cf-fe05-431c-aba1-03d8540e2005.png)

Our current launch option is something like the `export NODE_ENV=test && jest --watchAll --config jest.config.integration.cjs --maxWorkers 1`.

**Comment by SimenB** [comment]
This is a question for Jest, not this plugin.

That said, just run `--watch` instead of `--watchAll` and it should do what you want (unless you have changes locally, but `watchAll` forces jest to run all tests)
