### ISSUE TITLE
Error: Failed to initialize watch plugin: ".../jest-watch-typeahead/filename.js"

### ISSUE THREAD

**Issue by Robin-Hoodie** [jest-community/jest-watch-typeahead#133]
I ran into the above error and noticed 2 issues had been opened for this before

https://github.com/jest-community/jest-watch-typeahead/issues/99 got closed because no repro was provided

https://github.com/jest-community/jest-watch-typeahead/issues/98 got closed because no supported version of Node was used

Here is a repro: https://github.com/Robin-Hoodie/repro-jest-watch-typeahead - I used node `v16.13.1` to reproduce the error

**Comment by SimenB** [comment]
Thanks for the report with a reproduction!

You reproduction works if you upgrade yarn to 3.2.

`yarn set version latest && yarn && yarn test`

**Comment by Robin-Hoodie** [comment]
That works indeed, thanks for the swift answer and resolution @SimenB

**Comment by bhison** [comment]
Thank you so much to you both for a well structured question and an answer that worked for me. What I am confused by is that I have been developing a CRA app using NPM for my package manager. I've recently moved machine so had to install a lot of yarn dependencies. So is it the case that even if I use NPM as my top level package manager Yarn is still somehow a dependency?

Anyway, most importantly, somehow it is now all working!
