### ISSUE TITLE
First character(s) not rendering correctly in some terminals.

### ISSUE THREAD

**Issue by rogeliog** [jest-community/jest-watch-typeahead#20]
See for more details https://github.com/facebook/create-react-app/pull/5213#issue-219521126

There are a some issues when using typeahead in different terminals mainly (xterm vs screen)
We saw similar issues when the typeahead was still part of Jest core, specifically https://github.com/facebook/jest/pull/3392 and https://github.com/facebook/jest/pull/2594

<img width="596" alt="46316727-db68a700-c5c8-11e8-8b82-f7b1adea4e65" src="https://user-images.githubusercontent.com/574806/46452473-d0d91980-c750-11e8-9d79-612cc7b2b0c0.png">

<img width="283" alt="46316725-db68a700-c5c8-11e8-8f54-46b36ec27934" src="https://user-images.githubusercontent.com/574806/46452474-d171b000-c750-11e8-9973-ae4d52fffb21.png">

cc @gaearon

**Comment by SimenB** [comment]
`jest-watch-typeahead 0.2.1 published 🎉`
