### ISSUE TITLE
Support initial filter

### ISSUE THREAD

**Issue by unional** [jest-community/jest-watch-typeahead#22]
## Use case

When the test suite includes acceptance tests and you want to filter them out by default

```js
{
  "watchPlugins": [
    ["jest-watch-typeahead", { testPathPattern: "...", testNamePattern: "..." }]
  ]
}
```

**Comment by rogeliog** [comment]
You could pass this as CLI arguments to Jest today and it should work with and without this plugin

**Comment by rogeliog** [comment]
Seems to me that this can be closed. I'll do that, but feel free to reopen if needed.
