### ISSUE TITLE
Include describes in search results

### ISSUE THREAD

**Issue by BrendanBall** [jest-community/jest-watch-typeahead#24]
This plugin is awesome!
There's just one problem with the way we do testing. E.g. for basic crud tests there might be multiple nested describes in one file where tests in the same file but different describes end up having the same description e.g `test('permission')` which means when I use this plugin and search for `permission` there's multiple search results with the same test name and no way of differentiating between them to choose the right one.

I propose the search results should include the nested describes, possibly similar to how jest outputs test results with a hierarchy of describes and test descriptions.

**Comment by rogeliog** [comment]
I agree I think it should show the full test name, including the describe blocks.

I think this is a regression, from what I remember it used to do it? Maybe that was before it was moved out of Jest core

**Comment by SimenB** [comment]
It only looks at `title`: https://github.com/jest-community/jest-watch-typeahead/blob/f3f6eb18ea24ec4be83e4589fed60bcb0bf9c16b/src/test_name_plugin/prompt.js#L89-L95

It should look at `fullName` instead, I think https://github.com/facebook/jest/blob/50300ab1252e1e02de9a456f2edc60b2fac3bc8f/packages/jest-test-result/src/types.ts#L56

**Comment by rogeliog** [comment]
Yes, this is correct

**Comment by rogeliog** [comment]
I thought that this was a regression, but it seems that it has always used `title` https://github.com/facebook/jest/blob/9c429cd15d639ab42cfe0a9fa7032095af3b675f/packages/jest-cli/src/test_name_pattern_prompt.js#L92-L98, did the definition of `title` change recently to not include the describe blocks?

**Comment by SimenB** [comment]
I don't think so? You can install an old version of Jest to verify if it's a regression or not? Jest 21.2 removed the typeahead, so make sure `jest-cli` is older than that

**Comment by rogeliog** [comment]
I've been having some trouble setting up a local copy of `21.x`, but I just put up a PR for this #26
