### ISSUE TITLE
When selecting a specific test name the pattern should be exact

### ISSUE THREAD

**Issue by Andarist** [jest-community/jest-watch-typeahead#38]
When having 2 test names:
- "foo bar"
- "foo"

and selecting "foo" then the pattern should be `^foo$` instead of `foo`. After all - I've selected that specific test from the list and not merely an "expanded pattern". 

I've tried to implement this quickly as I've thought that this change would be trivial, but the interaction between `Prompt`, `TestNamePlugin`, and `TestNamePatternPrompt` is not that obvious. 

If you agree with the change I could dig more into seeing what it would take to implement this change.

**Comment by SimenB** [comment]
I agree - if you use the arrows to select you want to run that specific test

**Comment by jeysal** [comment]
Makes sense to me. Probably a rare case since file extensions are a thing, but we should still fix it

**Comment by SimenB** [comment]
This is test name, not _file_ name

**Comment by jeysal** [comment]
Oh god, remember the terminology discussion about that? 😅 Let's say it's about test case name, not test file name
