### ISSUE TITLE
Add NX Support Release

### ISSUE THREAD

**Issue by joshdegouveia** [jest-community/jest-watch-typeahead#45]
A recent commit added support for NX workspaces.
https://github.com/jest-community/jest-watch-typeahead/pull/34

@jeysal @SimenB @thymikee

Would it be possible to create a new release with this commit included?

**Comment by jeysal** [comment]
I don't have permission (that I know of)

**Comment by SimenB** [comment]
@jeysal you do have permissions (I've added the package to the community org on npm)

**Comment by jeysal** [comment]
Nope, getting 403 every attempt, no matter if logged in with `--scope=jest-community` or not. I've pushed a version commit and tag already, but can't publish

**Comment by SimenB** [comment]
it's out
