### ISSUE TITLE
Highlight misplaced

### ISSUE THREAD

**Issue by luanorlandi** [jest-community/jest-watch-typeahead#46]
Hello! I've installed jest-watch-typeahead successfully, though with one minor issue, the highlight color is misplaced:

![image](https://user-images.githubusercontent.com/6919329/113734285-9827ab80-96d1-11eb-8916-a86634bf1a8f.png)

Any ideas what could it be?

I'm using Mac, Node v14.0.0, Npm v6.14.4, zsh 5.7.1, with these lib versions:

```
"jest": "^26.6.3",
"jest-watch-typeahead": "^0.6.2",
```

This is my jest.config.js file:

```js
module.exports = {
  moduleFileExtensions: [
    'js',
    'json',
    'vue'
  ],
  moduleNameMapper: {
    '^(@|src)/(.*)$': '<rootDir>/src/$2',
    '^@fixtures/(.*)$': '<rootDir>/__fixtures__/$1'
  },
  transformIgnorePatterns: [
    '/node_modules/(?!vee-validate)/'
  ],
  transform: {
    '^.+\\.vue$': require.resolve('vue-jest'),
    '^.+\\.jsx?$': require.resolve('babel-jest'),
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/assetsTransformer.js'
  },
  setupFilesAfterEnv: ['<rootDir>/__tests__/setupFiles.js'],
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname'
  ]
}
```

The same occur with the Mac Terminal and VSCode embedded terminal, also the same thing with either zsh or bash

**Comment by jeysal** [comment]
Could be due to https://github.com/jest-community/jest-watch-typeahead/pull/34 ? It did not change any existing tests but possibly test coverage was insufficient to detect this breakage

**Comment by luanorlandi** [comment]
I tested with `jest-watch-typeahead@0.6.3` new release, that fixed the issue:

![image](https://user-images.githubusercontent.com/6919329/116409451-3c50ce00-a80a-11eb-8d3b-1e3745ebe282.png)

Nicely done everyone, and thank you for the amazing work in this lib! 🚀 🎉
