### ISSUE TITLE
THANK YOU!!!!!

### ISSUE THREAD

**Issue by kentcdodds** [jest-community/jest-watch-typeahead#5]
I just want to say thank you. You're the best!

**Comment by kentcdodds** [comment]
Just noticed that @rogeliog (who I believe is primarily responsible for this effort) is not watching the repo. This is for you friend! 💯 🥇

**Comment by rogeliog** [comment]
😊 😊 😊 Thanks a lot!!! 🙃 🙃 🙃 🙃
