### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by eps1lon** [jest-community/jest-watch-typeahead#61]
Now that jest 27 is released, could you publish the latest version of `jest-watch-typeahead` as well? The `peerDependencies` are already updated but the [published version does not allow jest 27 yet](https://unpkg.com/jest-watch-typeahead@latest/package.json). 

Using jest 27 + jest-watch-typeahead 0.6.3 leads to `npm ERR! ERESOLVE unable to resolve dependency tree` using the latest npm version: https://github.com/kentcdodds/kcd-scripts/pull/210

**Comment by SimenB** [comment]
Ah, I thought we had automatic release set up here. I'll publish a new version tonight or tomorrow (CEST)

**Comment by SimenB** [comment]
https://github.com/jest-community/jest-watch-typeahead/releases/tag/v0.6.4
