### ISSUE TITLE
Lodash version is fixed: should be `^`

### ISSUE THREAD

**Issue by kompot** [jest-community/jest-watch-typeahead#7]
Hey,
finally typeahead is here, thanks!

I noticed that lodash dep version is fixed
https://github.com/jest-community/jest-watch-typeahead/blob/master/package.json#L29
and not `^4.17.5`.

Seems like a bug to me. Is there a reason for that?

**Comment by SimenB** [comment]
We don't actually use lodash, I've dropped it in #6 🙂
